version: 2
updates:

  - package-ecosystem: "npm"
    directory: "/"
    # Check the crates registry for updates every day (weekdays)
    schedule:
      interval: "weekly"
    assignees:
      - "mukundbhudia"
