image: node:13.12.0 # change to match your node version

variables:
    PUBLIC_URL: "/covid-web"

cache:
  paths:
    - node_modules/

before_script:
  - npm install

pages:
  stage: deploy
  variables:
      PUBLIC_URL: "/covid-web"
  script:
    - export REACT_APP_GQL_URI=https://covid19-dash-api.herokuapp.com # set REACT_APP variables before build command
    - CI=true npm run build
    - rm -rf public
    - mv build public
    - cp public/index.html public/404.html
  artifacts:
    paths:
      - public # GitLab pages serve from a 'public' directory
  only:
    - master # run on master branch